baseURL = "https://mikerowecode.com/"
languageCode = "en-au"
title = "mikerowecode"
copyright = "© 2003-2019 Michael Rowe unless otherwise noted. All rights reserved."
theme = "tale"
googleAnalytics = "UA-6154615-1"

# for some of the older articles...
disablePathToLower = true

# configure code syntax highlighting
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "emacs"
# pygmentsOptions = "linenos=true"

[Params]
  css = ["/css/local.css"]

[author]
  name = "Michael Rowe"

[params]
  GitHubUser = "mrowe"

[permalinks]
  posts = "/:year/:month/:slug"
