baseURL = "https://mikerowecode.com/"
languageCode = "en-au"
title = "mikerowecode"
theme = "tale"
googleAnalytics = "UA-6154615-1"

# for some of the older articles...
disablePathToLower = true

[Author]
  name = "Michael Rowe"

[params]
  GitHubUser = "mrowe"

[permalinks]
  posts = "/:year/:month/:slug"
